USE artiste;

-- NOTE: Jobs
-- CREATE TABLE jobs (
--    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--    title VARCHAR(255) NOT NULL,
--    description VARCHAR(255),
--    pay INT
-- );
-- NOTE: Contractors
-- CREATE TABLE contractors (
--    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(255) NOT NULL,
--    contact VARCHAR(255) NOT NULL,
--    info VARCHAR(255)
-- );
-- NOTE: Assignments
-- CREATE TABLE assignments (
--    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--    jobId INT NOT NULL,
--    contractorId INT NOT NULL,
--    FOREIGN KEY (contractorId) REFERENCES contractors(id),
--    FOREIGN KEY (jobId) REFERENCES jobs(id)
-- );
-- 
-- SELECT
--    j.id AS JobId,
--    j.title,
--    j.description,
--    j.pay,
--    c.id AS ContractorId,
--    c.name,
--    c.contact,
--    c.info,
--    assignments.id AS AssignmentId
-- FROM
--    assignments
--    JOIN jobs j ON j.id = assignments.jobId
--    JOIN contractors c ON c.id = assignments.contractorId
-- WHERE
--    assignments.id = 5;
-- 
-- SELECT
--    c.*,
--    assignments.id AS AssignmentId
-- FROM
--    assignments
--    JOIN contractors c ON c.id = assignments.contractorId
-- WHERE
--    assignments.id = 5;